-- ============================================================
-- Project : IRON GYM MANAGEMENT SYSTEM (V4 - SYNCED)
-- Script  : 01_gym_setup.sql
-- Purpose : DDL - Create all 8 tables with exact app column names
-- ============================================================

SET SERVEROUTPUT ON;

-- Cleanup
BEGIN
    FOR i IN (SELECT table_name FROM user_tables) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || i.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;
    FOR i IN (SELECT sequence_name FROM user_sequences) LOOP
        EXECUTE IMMEDIATE 'DROP SEQUENCE ' || i.sequence_name;
    END LOOP;
END;
/

-- 1. STAFF Table
CREATE TABLE STAFF (
    STAFFID NUMBER(10) CONSTRAINT pk_staff PRIMARY KEY,
    FIRSTNAME VARCHAR2(50) NOT NULL,
    LASTNAME VARCHAR2(50) NOT NULL,
    ROLE VARCHAR2(20) CONSTRAINT chk_staff_role CHECK (ROLE IN ('Admin', 'Trainer', 'Cleaner')),
    PHONE VARCHAR2(15) CONSTRAINT uq_staff_phone UNIQUE,
    SALARY NUMBER(8,2) DEFAULT 0
);

-- 2. MEMBER Table
CREATE TABLE MEMBER (
    MEMBERID NUMBER(10) CONSTRAINT pk_member PRIMARY KEY,
    FIRSTNAME VARCHAR2(50) NOT NULL,
    LASTNAME VARCHAR2(50) NOT NULL,
    DATEOFBIRTH DATE,
    GENDER CHAR(1) CONSTRAINT chk_gender CHECK (GENDER IN ('M', 'F', 'O')),
    PHONE VARCHAR2(15) CONSTRAINT uq_member_phone UNIQUE NOT NULL,
    EMAIL VARCHAR2(100),
    REGISTRATIONDATE DATE DEFAULT SYSDATE,
    PASSWORD VARCHAR2(50) DEFAULT '1234'
);

-- 3. PLAN Table
CREATE TABLE MEMBERSHIP_PLAN (
    PLANID NUMBER(10) CONSTRAINT pk_plan PRIMARY KEY,
    PLAN_NAME VARCHAR2(50) NOT NULL,
    PRICE NUMBER(8,2) NOT NULL,
    DURATION_DAYS NUMBER(4) NOT NULL
);

-- 4. EQUIPMENT Table
CREATE TABLE EQUIPMENT (
    EQUIPMENTID NUMBER(10) CONSTRAINT pk_equip PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    STATUS VARCHAR2(20) CONSTRAINT chk_equip_status CHECK (STATUS IN ('Working', 'Broken', 'Maintenance')),
    PURCHASE_DATE DATE DEFAULT SYSDATE
);

-- 5. CLASS Table
CREATE TABLE GYM_CLASS (
    CLASSID NUMBER(10) CONSTRAINT pk_class PRIMARY KEY,
    CLASS_NAME VARCHAR2(100) NOT NULL,
    TRAINER_ID NUMBER(10),
    SCHEDULE_TIME VARCHAR2(20),
    CAPACITY NUMBER(3),
    CONSTRAINT fk_class_trainer FOREIGN KEY (TRAINER_ID) REFERENCES STAFF(STAFFID) ON DELETE SET NULL
);

-- 6. ATTENDANCE Table
CREATE TABLE ATTENDANCE (
    MEMBERID NUMBER(10),
    ATTENDANCE_DATE DATE,
    STATUS VARCHAR2(10) CHECK (STATUS IN ('Present', 'Absent')),
    CONSTRAINT pk_attendance PRIMARY KEY (MEMBERID, ATTENDANCE_DATE),
    CONSTRAINT fk_att_member FOREIGN KEY (MEMBERID) REFERENCES MEMBER(MEMBERID) ON DELETE CASCADE
);

-- 7. PAYMENT Table
CREATE TABLE PAYMENT (
    PAYMENTID NUMBER(10) CONSTRAINT pk_payment PRIMARY KEY,
    MEMBERID NUMBER(10) NOT NULL,
    AMOUNT NUMBER(8,2) NOT NULL,
    PAYMENT_DATE DATE DEFAULT SYSDATE,
    METHOD VARCHAR2(20) CHECK (METHOD IN ('Cash', 'Card', 'Online')),
    CONSTRAINT fk_pay_member FOREIGN KEY (MEMBERID) REFERENCES MEMBER(MEMBERID) ON DELETE CASCADE
);

-- 8. AUDIT_LOG Table
CREATE TABLE AUDIT_LOG (
    LOGID NUMBER(10) CONSTRAINT pk_log PRIMARY KEY,
    ACTION_NAME VARCHAR2(100),
    ACTION_DATE DATE DEFAULT SYSDATE,
    USER_NAME VARCHAR2(50)
);

-- Sequences
CREATE SEQUENCE SEQ_STAFF_ID START WITH 1;
CREATE SEQUENCE SEQ_MEMBER_ID START WITH 1001;
CREATE SEQUENCE SEQ_PLAN_ID START WITH 1;
CREATE SEQUENCE SEQ_EQUIP_ID START WITH 1;
CREATE SEQUENCE SEQ_PAY_ID START WITH 5001;
CREATE SEQUENCE SEQ_LOG_ID START WITH 1;

COMMIT;
